export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];

export interface Database {
  public: {
    Tables: {
      organizations: { Row: { id: string; name: string; slug: string; legal_name: string | null; registration_number: string | null; tax_id: string | null; email: string | null; phone: string | null; website: string | null; logo_url: string | null; status: string; subscription_plan: string; subscription_expires_at: string | null; settings: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["organizations"]["Row"]> & { name: string; slug: string }; Update: Partial<Database["public"]["Tables"]["organizations"]["Row"]> };
      tenants: { Row: { id: string; organization_id: string; name: string; slug: string; domain: string | null; logo_url: string | null; favicon_url: string | null; primary_color: string; secondary_color: string; status: string; subscription_plan: string; subscription_expires_at: string | null; max_users: number; max_students: number; max_storage_mb: number; timezone: string; locale: string; currency: string; date_format: string; settings: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["tenants"]["Row"]> & { organization_id: string; name: string; slug: string }; Update: Partial<Database["public"]["Tables"]["tenants"]["Row"]> };
      profiles: { Row: { id: string; tenant_id: string | null; first_name: string | null; last_name: string | null; display_name: string | null; avatar_url: string | null; date_of_birth: string | null; gender: string | null; bio: string | null; locale: string; timezone: string; status: string; last_login_at: string | null; last_active_at: string | null; login_count: number; preferences: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["profiles"]["Row"]> & { id: string }; Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]> };
      roles: { Row: { id: string; tenant_id: string | null; name: string; slug: string; description: string | null; is_system: boolean; is_default: boolean; level: number; color: string | null; icon: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["roles"]["Row"]> & { name: string; slug: string }; Update: Partial<Database["public"]["Tables"]["roles"]["Row"]> };
      permissions: { Row: { id: string; tenant_id: string | null; name: string; slug: string; module: string; action: string; resource: string | null; description: string | null; is_system: boolean; effect: string; conditions: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["permissions"]["Row"]> & { name: string; slug: string; module: string; action: string }; Update: Partial<Database["public"]["Tables"]["permissions"]["Row"]> };
      role_permissions: { Row: { id: string; tenant_id: string | null; role_id: string; permission_id: string; effect: string; conditions: Json; created_at: string; created_by: string | null }; Insert: Partial<Database["public"]["Tables"]["role_permissions"]["Row"]> & { role_id: string; permission_id: string }; Update: Partial<Database["public"]["Tables"]["role_permissions"]["Row"]> };
      user_roles: { Row: { id: string; tenant_id: string | null; user_id: string; role_id: string; assigned_at: string; expires_at: string | null; is_active: boolean; metadata: Json; created_at: string; updated_at: string; created_by: string | null }; Insert: Partial<Database["public"]["Tables"]["user_roles"]["Row"]> & { user_id: string; role_id: string }; Update: Partial<Database["public"]["Tables"]["user_roles"]["Row"]> };
      students: { Row: { id: string; tenant_id: string; user_id: string | null; student_number: string; admission_date: string | null; status: string; academic_level: string; guardian_name: string | null; guardian_phone: string | null; guardian_email: string | null; guardian_relationship: string | null; emergency_contact_name: string | null; emergency_contact_phone: string | null; medical_conditions: string | null; allergies: string | null; blood_group: string | null; nationality: string | null; religion: string | null; place_of_birth: string | null; previous_school: string | null; previous_grade: string | null; notes: string | null; tags: string[]; custom_fields: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["students"]["Row"]> & { tenant_id: string; student_number: string }; Update: Partial<Database["public"]["Tables"]["students"]["Row"]> };
      student_enrollments: { Row: { id: string; tenant_id: string; student_id: string; course_id: string; class_id: string | null; enrollment_date: string; start_date: string | null; end_date: string | null; status: string; payment_status: string; total_fees: number; paid_amount: number; discount_amount: number; discount_reason: string | null; notes: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["student_enrollments"]["Row"]> & { tenant_id: string; student_id: string; course_id: string }; Update: Partial<Database["public"]["Tables"]["student_enrollments"]["Row"]> };
      courses: { Row: { id: string; tenant_id: string; program_id: string | null; department_id: string | null; instructor_id: string | null; name: string; code: string; description: string | null; academic_level: string; status: string; credits: number; duration_hours: number | null; max_students: number | null; min_students: number; price: number; currency: string; start_date: string | null; end_date: string | null; schedule: Json; prerequisites: string[]; syllabus: string | null; objectives: string | null; materials: string | null; is_online: boolean; online_link: string | null; location: string | null; image_url: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["courses"]["Row"]> & { tenant_id: string; name: string; code: string }; Update: Partial<Database["public"]["Tables"]["courses"]["Row"]> };
      classes: { Row: { id: string; tenant_id: string; course_id: string; semester_id: string | null; instructor_id: string | null; name: string; code: string; section: string | null; status: string; max_students: number | null; current_students: number; start_date: string | null; end_date: string | null; schedule: Json; room: string | null; building: string | null; is_active: boolean; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["classes"]["Row"]> & { tenant_id: string; course_id: string; name: string; code: string }; Update: Partial<Database["public"]["Tables"]["classes"]["Row"]> };
      programs: { Row: { id: string; tenant_id: string; department_id: string | null; name: string; code: string; description: string | null; academic_level: string; duration_months: number | null; total_credits: number | null; total_courses: number | null; is_active: boolean; requirements: string | null; outcomes: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["programs"]["Row"]> & { tenant_id: string; name: string; code: string }; Update: Partial<Database["public"]["Tables"]["programs"]["Row"]> };
      departments: { Row: { id: string; tenant_id: string; parent_id: string | null; name: string; code: string; description: string | null; head_id: string | null; email: string | null; phone: string | null; is_active: boolean; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["departments"]["Row"]> & { tenant_id: string; name: string; code: string }; Update: Partial<Database["public"]["Tables"]["departments"]["Row"]> };
      instructors: { Row: { id: string; tenant_id: string; user_id: string; department_id: string | null; employee_number: string | null; specialization: string | null; qualifications: string | null; experience_years: number; hourly_rate: number | null; bio: string | null; office_location: string | null; office_hours: string | null; is_active: boolean; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["instructors"]["Row"]> & { tenant_id: string; user_id: string }; Update: Partial<Database["public"]["Tables"]["instructors"]["Row"]> };
      invoices: { Row: { id: string; tenant_id: string; student_id: string; invoice_number: string; status: string; issue_date: string; due_date: string; subtotal: number; tax_amount: number; discount_amount: number; total_amount: number; paid_amount: number; balance: number; currency: string; notes: string | null; terms: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["invoices"]["Row"]> & { tenant_id: string; student_id: string; invoice_number: string; due_date: string }; Update: Partial<Database["public"]["Tables"]["invoices"]["Row"]> };
      payments: { Row: { id: string; tenant_id: string; student_id: string; invoice_id: string | null; payment_number: string; amount: number; currency: string; payment_method: string; payment_date: string; status: string; reference_number: string | null; transaction_id: string | null; notes: string | null; receipt_url: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["payments"]["Row"]> & { tenant_id: string; student_id: string; payment_number: string; amount: number }; Update: Partial<Database["public"]["Tables"]["payments"]["Row"]> };
      attendance_records: { Row: { id: string; tenant_id: string; student_id: string; class_id: string; session_id: string | null; attendance_date: string; status: string; check_in_time: string | null; check_out_time: string | null; late_minutes: number; reason: string | null; notes: string | null; marked_by: string | null; is_approved: boolean; approved_by: string | null; approved_at: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["attendance_records"]["Row"]> & { tenant_id: string; student_id: string; class_id: string }; Update: Partial<Database["public"]["Tables"]["attendance_records"]["Row"]> };
      attendance_summary: { Row: { id: string; tenant_id: string; student_id: string; class_id: string; month: number; year: number; total_sessions: number; present_count: number; absent_count: number; late_count: number; excused_count: number; attendance_percentage: number; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["attendance_summary"]["Row"]> & { tenant_id: string; student_id: string; class_id: string; month: number; year: number }; Update: Partial<Database["public"]["Tables"]["attendance_summary"]["Row"]> };
      announcements: { Row: { id: string; tenant_id: string; author_id: string; type: string; title: string; content: string; summary: string | null; image_url: string | null; is_pinned: boolean; is_published: boolean; published_at: string | null; expires_at: string | null; target_roles: string[]; target_users: string[]; view_count: number; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["announcements"]["Row"]> & { tenant_id: string; author_id: string; title: string; content: string }; Update: Partial<Database["public"]["Tables"]["announcements"]["Row"]> };
      calendar_events: { Row: { id: string; tenant_id: string; organizer_id: string; type: string; title: string; description: string | null; location: string | null; start_time: string; end_time: string; all_day: boolean; recurrence: string; recurrence_end_date: string | null; color: string | null; is_public: boolean; max_attendees: number | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["calendar_events"]["Row"]> & { tenant_id: string; organizer_id: string; title: string; start_time: string; end_time: string }; Update: Partial<Database["public"]["Tables"]["calendar_events"]["Row"]> };
      tasks: { Row: { id: string; tenant_id: string; assigned_to: string | null; assigned_by: string | null; parent_task_id: string | null; title: string; description: string | null; status: string; priority: string; due_date: string | null; completed_at: string | null; estimated_hours: number | null; actual_hours: number | null; progress: number; tags: string[]; attachments: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["tasks"]["Row"]> & { tenant_id: string; title: string }; Update: Partial<Database["public"]["Tables"]["tasks"]["Row"]> };
      notifications: { Row: { id: string; tenant_id: string; user_id: string; type: string; channel: string; title: string; body: string | null; data: Json; read_at: string | null; sent_at: string | null; expires_at: string | null; is_read: boolean; is_sent: boolean; action_url: string | null; action_label: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null }; Insert: Partial<Database["public"]["Tables"]["notifications"]["Row"]> & { tenant_id: string; user_id: string; title: string }; Update: Partial<Database["public"]["Tables"]["notifications"]["Row"]> };
      messages: { Row: { id: string; tenant_id: string; sender_id: string; recipient_id: string | null; conversation_id: string | null; parent_message_id: string | null; subject: string | null; body: string; status: string; is_broadcast: boolean; read_at: string | null; attachments: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null }; Insert: Partial<Database["public"]["Tables"]["messages"]["Row"]> & { tenant_id: string; sender_id: string; body: string }; Update: Partial<Database["public"]["Tables"]["messages"]["Row"]> };
      conversations: { Row: { id: string; tenant_id: string; title: string | null; type: string; last_message_at: string | null; last_message_preview: string | null; is_archived: boolean; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null }; Insert: Partial<Database["public"]["Tables"]["conversations"]["Row"]> & { tenant_id: string }; Update: Partial<Database["public"]["Tables"]["conversations"]["Row"]> };
      documents: { Row: { id: string; tenant_id: string; uploaded_by: string; documentable_type: string | null; documentable_id: string | null; type: string; name: string; description: string | null; file_path: string; file_size: number | null; mime_type: string | null; version: number; is_public: boolean; is_encrypted: boolean; checksum: string | null; tags: string[]; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["documents"]["Row"]> & { tenant_id: string; uploaded_by: string; name: string; file_path: string }; Update: Partial<Database["public"]["Tables"]["documents"]["Row"]> };
      reports: { Row: { id: string; tenant_id: string; created_by: string; name: string; description: string | null; type: string; format: string; query_config: Json; filters: Json; schedule: Json; is_scheduled: boolean; last_run_at: string | null; next_run_at: string | null; file_path: string | null; file_size: number | null; run_count: number; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["reports"]["Row"]> & { tenant_id: string; created_by: string; name: string; type: string; query_config: Json }; Update: Partial<Database["public"]["Tables"]["reports"]["Row"]> };
      academic_years: { Row: { id: string; tenant_id: string; name: string; code: string; start_date: string; end_date: string; is_current: boolean; is_active: boolean; description: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["academic_years"]["Row"]> & { tenant_id: string; name: string; code: string; start_date: string; end_date: string }; Update: Partial<Database["public"]["Tables"]["academic_years"]["Row"]> };
      semesters: { Row: { id: string; tenant_id: string; academic_year_id: string; name: string; code: string; start_date: string; end_date: string; is_current: boolean; is_active: boolean; description: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["semesters"]["Row"]> & { tenant_id: string; academic_year_id: string; name: string; code: string; start_date: string; end_date: string }; Update: Partial<Database["public"]["Tables"]["semesters"]["Row"]> };
      fee_structures: { Row: { id: string; tenant_id: string; name: string; code: string; description: string | null; academic_year_id: string | null; program_id: string | null; amount: number; currency: string; fee_type: string; is_mandatory: boolean; is_active: boolean; due_days: number; late_fee_amount: number; late_fee_percentage: number; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["fee_structures"]["Row"]> & { tenant_id: string; name: string; code: string; amount: number }; Update: Partial<Database["public"]["Tables"]["fee_structures"]["Row"]> };
      scholarships: { Row: { id: string; tenant_id: string; name: string; code: string; description: string | null; type: string; value: number; value_type: string; max_recipients: number | null; current_recipients: number; academic_year_id: string | null; criteria: Json; is_active: boolean; start_date: string | null; end_date: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["scholarships"]["Row"]> & { tenant_id: string; name: string; code: string; value: number; value_type: string }; Update: Partial<Database["public"]["Tables"]["scholarships"]["Row"]> };
      discounts: { Row: { id: string; tenant_id: string; name: string; code: string; description: string | null; type: string; value: number; min_amount: number; max_discount: number | null; usage_limit: number | null; used_count: number; is_active: boolean; start_date: string | null; end_date: string | null; applicable_fees: string[]; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["discounts"]["Row"]> & { tenant_id: string; name: string; code: string; value: number; type: string }; Update: Partial<Database["public"]["Tables"]["discounts"]["Row"]> };
      transactions: { Row: { id: string; tenant_id: string; payment_id: string | null; type: string; category: string; subcategory: string | null; amount: number; currency: string; description: string | null; reference: string | null; transaction_date: string; is_reconciled: boolean; reconciled_at: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["transactions"]["Row"]> & { tenant_id: string; type: string; category: string; amount: number }; Update: Partial<Database["public"]["Tables"]["transactions"]["Row"]> };
      invoice_items: { Row: { id: string; tenant_id: string; invoice_id: string; fee_structure_id: string | null; description: string; quantity: number; unit_price: number; amount: number; tax_rate: number; tax_amount: number; discount_amount: number; total_amount: number; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["invoice_items"]["Row"]> & { tenant_id: string; invoice_id: string; description: string }; Update: Partial<Database["public"]["Tables"]["invoice_items"]["Row"]> };
      student_documents: { Row: { id: string; tenant_id: string; student_id: string; document_id: string; document_type: string; title: string; description: string | null; issue_date: string | null; expiry_date: string | null; is_verified: boolean; verified_by: string | null; verified_at: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["student_documents"]["Row"]> & { tenant_id: string; student_id: string; document_id: string; document_type: string; title: string }; Update: Partial<Database["public"]["Tables"]["student_documents"]["Row"]> };
      student_notes: { Row: { id: string; tenant_id: string; student_id: string; author_id: string; title: string | null; content: string; is_private: boolean; is_pinned: boolean; tags: string[]; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["student_notes"]["Row"]> & { tenant_id: string; student_id: string; author_id: string; content: string }; Update: Partial<Database["public"]["Tables"]["student_notes"]["Row"]> };
      student_scholarships: { Row: { id: string; tenant_id: string; student_id: string; scholarship_id: string; amount: number; status: string; start_date: string; end_date: string | null; notes: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["student_scholarships"]["Row"]> & { tenant_id: string; student_id: string; scholarship_id: string; amount: number; start_date: string }; Update: Partial<Database["public"]["Tables"]["student_scholarships"]["Row"]> };
      contacts: { Row: { id: string; tenant_id: string; contactable_type: string | null; contactable_id: string | null; contact_type: string; value: string; is_primary: boolean; is_verified: boolean; verified_at: string | null; label: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["contacts"]["Row"]> & { tenant_id: string; contact_type: string; value: string }; Update: Partial<Database["public"]["Tables"]["contacts"]["Row"]> };
      addresses: { Row: { id: string; tenant_id: string; addressable_type: string | null; addressable_id: string | null; address_type: string; line1: string | null; line2: string | null; city: string | null; state: string | null; postal_code: string | null; country: string; is_primary: boolean; latitude: number | null; longitude: number | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["addresses"]["Row"]> & { tenant_id: string; address_type: string }; Update: Partial<Database["public"]["Tables"]["addresses"]["Row"]> };
      audit_logs: { Row: { id: string; tenant_id: string | null; user_id: string | null; action: string; resource_type: string; resource_id: string | null; old_values: Json; new_values: Json; ip_address: string | null; user_agent: string | null; session_id: string | null; request_id: string | null; metadata: Json; created_at: string }; Insert: Partial<Database["public"]["Tables"]["audit_logs"]["Row"]>; Update: never };
      system_settings: { Row: { id: string; tenant_id: string | null; key: string; value: string | null; value_type: string; category: string; description: string | null; is_public: boolean; is_encrypted: boolean; validation_rules: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["system_settings"]["Row"]> & { key: string; category: string }; Update: Partial<Database["public"]["Tables"]["system_settings"]["Row"]> };
      calendar_event_attendees: { Row: { id: string; tenant_id: string; event_id: string; user_id: string; status: string; response_at: string | null; notes: string | null; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["calendar_event_attendees"]["Row"]> & { event_id: string; user_id: string }; Update: Partial<Database["public"]["Tables"]["calendar_event_attendees"]["Row"]> };
      conversation_participants: { Row: { id: string; tenant_id: string; conversation_id: string; user_id: string; joined_at: string; last_read_at: string | null; is_muted: boolean; is_pinned: boolean; metadata: Json; created_at: string; updated_at: string }; Insert: Partial<Database["public"]["Tables"]["conversation_participants"]["Row"]> & { conversation_id: string; user_id: string }; Update: Partial<Database["public"]["Tables"]["conversation_participants"]["Row"]> };
      attendance_policies: { Row: { id: string; tenant_id: string; name: string; description: string | null; min_attendance_percentage: number; late_threshold_minutes: number; auto_mark_absent: boolean; allow_excuse: boolean; excuse_required_document: boolean; notification_enabled: boolean; notification_threshold: number; is_active: boolean; applicable_programs: string[]; applicable_levels: string[]; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["attendance_policies"]["Row"]> & { tenant_id: string; name: string }; Update: Partial<Database["public"]["Tables"]["attendance_policies"]["Row"]> };
      attendance_excuses: { Row: { id: string; tenant_id: string; attendance_id: string; student_id: string; reason: string; document_id: string | null; status: string; reviewed_by: string | null; reviewed_at: string | null; review_notes: string | null; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["attendance_excuses"]["Row"]> & { tenant_id: string; attendance_id: string; student_id: string; reason: string }; Update: Partial<Database["public"]["Tables"]["attendance_excuses"]["Row"]> };
      class_schedules: { Row: { id: string; tenant_id: string; class_id: string; day_of_week: number; start_time: string; end_time: string; room: string | null; building: string | null; is_active: boolean; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["class_schedules"]["Row"]> & { tenant_id: string; class_id: string; day_of_week: number; start_time: string; end_time: string }; Update: Partial<Database["public"]["Tables"]["class_schedules"]["Row"]> };
      class_sessions: { Row: { id: string; tenant_id: string; class_id: string; instructor_id: string | null; title: string | null; description: string | null; session_date: string; start_time: string; end_time: string; room: string | null; building: string | null; status: string; notes: string | null; materials: Json; metadata: Json; created_at: string; updated_at: string; deleted_at: string | null; created_by: string | null; updated_by: string | null }; Insert: Partial<Database["public"]["Tables"]["class_sessions"]["Row"]> & { tenant_id: string; class_id: string; session_date: string; start_time: string; end_time: string }; Update: Partial<Database["public"]["Tables"]["class_sessions"]["Row"]> };
    };
    Views: Record<string, never>;
    Functions: {
      get_user_tenant_id: { Args: Record<string, never>; Returns: string };
      has_role: { Args: { role_slug: string }; Returns: boolean };
      has_permission: { Args: { permission_slug: string }; Returns: boolean };
      is_super_admin: { Args: Record<string, never>; Returns: boolean };
      is_tenant_admin: { Args: Record<string, never>; Returns: boolean };
      user_belongs_to_tenant: { Args: { target_tenant_id: string }; Returns: boolean };
      calculate_attendance_percentage: { Args: { p_student_id: string; p_class_id: string; p_tenant_id: string }; Returns: number };
    };
    Enums: Record<string, string>;
  };
}
